// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: feedback.proto

package feedbackpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_feedback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_feedback_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Feedback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *UUID                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Priority      string                 `protobuf:"bytes,4,opt,name=priority,proto3" json:"priority,omitempty"`
	TaskId        *UUID                  `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ProjectId     *UUID                  `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CreatedDate   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	Direction     string                 `protobuf:"bytes,8,opt,name=direction,proto3" json:"direction,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feedback) Reset() {
	*x = Feedback{}
	mi := &file_feedback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feedback) ProtoMessage() {}

func (x *Feedback) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feedback.ProtoReflect.Descriptor instead.
func (*Feedback) Descriptor() ([]byte, []int) {
	return file_feedback_proto_rawDescGZIP(), []int{1}
}

func (x *Feedback) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Feedback) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Feedback) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Feedback) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Feedback) GetTaskId() *UUID {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *Feedback) GetProjectId() *UUID {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

func (x *Feedback) GetCreatedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedDate
	}
	return nil
}

func (x *Feedback) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *Feedback) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListFeedbacksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Feedback              `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"` // можно использовать для фильтрации
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedbacksRequest) Reset() {
	*x = ListFeedbacksRequest{}
	mi := &file_feedback_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedbacksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedbacksRequest) ProtoMessage() {}

func (x *ListFeedbacksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedbacksRequest.ProtoReflect.Descriptor instead.
func (*ListFeedbacksRequest) Descriptor() ([]byte, []int) {
	return file_feedback_proto_rawDescGZIP(), []int{2}
}

func (x *ListFeedbacksRequest) GetFilter() *Feedback {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListFeedbacksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feedbacks     []*Feedback            `protobuf:"bytes,1,rep,name=feedbacks,proto3" json:"feedbacks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedbacksResponse) Reset() {
	*x = ListFeedbacksResponse{}
	mi := &file_feedback_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedbacksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedbacksResponse) ProtoMessage() {}

func (x *ListFeedbacksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedbacksResponse.ProtoReflect.Descriptor instead.
func (*ListFeedbacksResponse) Descriptor() ([]byte, []int) {
	return file_feedback_proto_rawDescGZIP(), []int{3}
}

func (x *ListFeedbacksResponse) GetFeedbacks() []*Feedback {
	if x != nil {
		return x.Feedbacks
	}
	return nil
}

var File_feedback_proto protoreflect.FileDescriptor

const file_feedback_proto_rawDesc = "" +
	"\n" +
	"\x0efeedback.proto\x12\bfeedback\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1c\n" +
	"\x04UUID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\xbb\x02\n" +
	"\bFeedback\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\v2\x0e.feedback.UUIDR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\tR\bpriority\x12'\n" +
	"\atask_id\x18\x05 \x01(\v2\x0e.feedback.UUIDR\x06taskId\x12-\n" +
	"\n" +
	"project_id\x18\x06 \x01(\v2\x0e.feedback.UUIDR\tprojectId\x12=\n" +
	"\fcreated_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedDate\x12\x1c\n" +
	"\tdirection\x18\b \x01(\tR\tdirection\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"B\n" +
	"\x14ListFeedbacksRequest\x12*\n" +
	"\x06filter\x18\x01 \x01(\v2\x12.feedback.FeedbackR\x06filter\"I\n" +
	"\x15ListFeedbacksResponse\x120\n" +
	"\tfeedbacks\x18\x01 \x03(\v2\x12.feedback.FeedbackR\tfeedbacks2c\n" +
	"\x0fFeedbackService\x12P\n" +
	"\rListFeedbacks\x12\x1e.feedback.ListFeedbacksRequest\x1a\x1f.feedback.ListFeedbacksResponseB-Z+your_project_path/gen/feedbackpb;feedbackpbb\x06proto3"

var (
	file_feedback_proto_rawDescOnce sync.Once
	file_feedback_proto_rawDescData []byte
)

func file_feedback_proto_rawDescGZIP() []byte {
	file_feedback_proto_rawDescOnce.Do(func() {
		file_feedback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feedback_proto_rawDesc), len(file_feedback_proto_rawDesc)))
	})
	return file_feedback_proto_rawDescData
}

var file_feedback_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_feedback_proto_goTypes = []any{
	(*UUID)(nil),                  // 0: feedback.UUID
	(*Feedback)(nil),              // 1: feedback.Feedback
	(*ListFeedbacksRequest)(nil),  // 2: feedback.ListFeedbacksRequest
	(*ListFeedbacksResponse)(nil), // 3: feedback.ListFeedbacksResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_feedback_proto_depIdxs = []int32{
	0, // 0: feedback.Feedback.id:type_name -> feedback.UUID
	0, // 1: feedback.Feedback.task_id:type_name -> feedback.UUID
	0, // 2: feedback.Feedback.project_id:type_name -> feedback.UUID
	4, // 3: feedback.Feedback.created_date:type_name -> google.protobuf.Timestamp
	1, // 4: feedback.ListFeedbacksRequest.filter:type_name -> feedback.Feedback
	1, // 5: feedback.ListFeedbacksResponse.feedbacks:type_name -> feedback.Feedback
	2, // 6: feedback.FeedbackService.ListFeedbacks:input_type -> feedback.ListFeedbacksRequest
	3, // 7: feedback.FeedbackService.ListFeedbacks:output_type -> feedback.ListFeedbacksResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_feedback_proto_init() }
func file_feedback_proto_init() {
	if File_feedback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedback_proto_rawDesc), len(file_feedback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feedback_proto_goTypes,
		DependencyIndexes: file_feedback_proto_depIdxs,
		MessageInfos:      file_feedback_proto_msgTypes,
	}.Build()
	File_feedback_proto = out.File
	file_feedback_proto_goTypes = nil
	file_feedback_proto_depIdxs = nil
}
