-- +goose Up
-- +goose StatementBegin
CREATE TABLE tg_messages (
    tg_message_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    chat_id BIGINT NOT NULL,
    message_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    text TEXT NOT NULL,
    UNIQUE (chat_id, message_id)
);
CREATE INDEX tg_messages_created_at_idx ON tg_messages (created_at);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE tg_messages;
-- +goose StatementEnd
