server:
  port: 3001

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Accept"
    - "Authorization"
    - "Content-Type"
    - "Set-Cookie"
    - "Refresh"
    - "X-CSRF-Token"
  allow_credentials: true
  max_age: 300

notion:
  sync_interval: 5m
  databases:
    projects: "fabaf12623a84b958b7d9fd780e0f7b8"
    tasks: "42fcf76e4ea2407ca3b8d71674a3fef8"
    times: "36b8bd637246476db6fb51fce18e795f"
    employees: "6807e199ff4247daac765cd9f29c184d"
    expertise: "f86c3388749c412c801e6edf1a8dfc22"
    feedback: "1ca27b05040480a79afbf179126afd10"
    weekday: "7e37b765927a4df3935834a738f2b9bd"
    topics: "22127b05040480a49b6ce654dbf66be9"
    client: "19ac829c5a9c42c5ac6a23bd83847aa6"
  
sheets:
  id: "1dStGuMfFU2Vq2V2xgXLyKUq_j3zYBeP15LA0eUQtTAQ"
  time_sheet: "Time"
  task_sheet: "Task"
  clients_sheet: "Clients"
  projects_sheet: "Project"